- name: Install Packages
  ansible.builtin.dnf: 
    name: "{{ es_install_packages }}"
    state: present
  notify: restart_services

- name: Copy config file
  ansible.builtin.copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  notify: restart_services
      
- name: Copy Kibana config file
  ansible.builtin.template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart_services

